- name: Copy content of directory 'frontend'
  copy:
    src: /workspace/kiv-dce-semestral-work/semestral/demo-3/frontend/    # note the '/' <-- !!!
    dest: /tmp/frontend/

- name: install nginx
  apt: name=nginx state=present
    

- name: Copy Nginx Config - default
  copy:
    src: /workspace/kiv-dce-semestral-work/semestral/demo-3/frontend/nginx/default
    dest: /etc/nginx/sites-available/default
  notify: Restart Nginx # viz handlers/main.yml 

- name: Create a folder
  ansible.builtin.file:
    path: /etc/nginx/default.d
    state: directory

- name: Copy Nginx Config - config/backend-upstream.conf
  copy:
    src: /workspace/kiv-dce-semestral-work/semestral/demo-3/frontend/config/backend-upstream.conf
    dest: /etc/nginx/conf.d/backend-upstream.conf
  notify: Restart Nginx  # viz handlers/main.yml 


- name: Check Nginx config
  become: true
  shell: nginx -t 
