- name: Copy content of directory 'backend'
  copy:
    src: /workspace/kiv-dce-semestral-work/semestral/demo-3/backend/    # note the '/' <-- !!!
    dest: /tmp/backend/

- name: Build backend image
  community.docker.docker_image:
    build:
      path: /tmp/backend/
    name: backend
    tag: v1
    push: false
    source: build

- name: Run Docker container
  docker_container:
    name: backend_container
    image: backend:v1
    state: started
    ports:
      "5000:5000"